#prometheus_treecache_zookeeper_failures_total - ZooKeeper failures
#prometheus_target_scrapes_sample_out_of_order_total - rejected OutOfOrder samples
#prometheus_target_scrapes_sample_out_of_bounds_total - rejescted samples OutOfTimebounds
#prometheus_target_scrapes_sample_duplicate_timestamp_total - rejected duplicated samples with different values
#prometheus_target_scrapes_exceeded_sample_limit_total - rejected scrapes due to sample limit

#prometheus_sd_triton_refresh_failures_total - triton scrape failures
#prometheus_sd_openstack_refresh_failures_total - Openstack scrape failures
#prometheus_sd_marathon_refresh_failures_total - Marathon refresh failures
#prometheus_sd_gce_refresh_failures_total - GCE refresh failures
#prometheus_sd_file_read_errors_total - File discovery read error
#prometheus_sd_ec2_refresh_failures_total - EC2 discovery failures
#prometheus_sd_dns_lookup_failures_total - DNS discovery failures
#prometheus_sd_consul_rpc_failures_total - Consul discovery failures
#prometheus_sd_azure_refresh_failures_total - Azure discovery failures

#prometheus_rule_group_iterations_missed_total - Group iteration missed
#prometheus_rule_evaluation_failures_total - Rule evaluation failure

#prometheus_notifications_queue_length - Number of elements in an alert queue
#prometheus_notifications_dropped_total - Number of alerts dropped
#prometheus_notifications_alertmanagers_discovered - number of active alert managers

#prometheus_engine_queries - number of queries waiting

#prometheus_config_last_reload_successful - successful reload

##from github.com/mwitkow/go-conntrack/dialer_reporter.go
#net_conntrack_dialer_conn_failed_total - connections failed
groups:
- name: Prometheus rules
  rules:
  - alert: PrometheusWALCorruptions
    expr: delta(prometheus_tsdb_wal_corruptions_total[1m]) > 0
    labels:
      severity: critical
    annotations:
      description: '{{$labels.instance}} reports critical problems with Write Ahead Logs. Some samples can be missing'
      summary: WAL corruptions on {{$labels.instance}}
  - alert: PrometheusWALCompactionsFailures
    expr: delta(prometheus_tsdb_compactions_failed_total[1m]) > 0
    labels:
      severity: warning
    annotations:
      description: '{{$labels.instance}} reports problems with Write Ahead Logs compaction. It can impact node performance'
      summary: WAL compaction failures on {{$labels.instance}}
